create table if not exists price_data (
    tick,
    timestamp,
    open,
    high,
    low,
    close,
    adjusted_close,
    volume,
    dividend_amount,
    primary key (tick, timestamp),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);
create table if not exists earnings_data (
    tick,
    timestamp,
    reported_date,
    reported_EPS,
    estimated_EPS,
    surprise,
    surprise_percentage,
    primary key (tick, timestamp),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);
create table if not exists company_data (
    tick primary key,
    Asset_Type,
    Name,
    Description,
    CIK,
    Exchange,
    Currency,
    Country,
    Sector,
    Industry,
    Address,
    Fiscal_Year_End,
    Latest_Quarter,
    Market_Capitalization,
    EBITDA,
    PE_Ratio,
    PEG_Ratio,
    Book_Value,
    Dividend_Per_Share,
    Dividend_Yield,
    EPS,
    Revenue_Per_Share_TTM,
    Profit_Margin,
    Operating_Margin_TTM,
    Return_On_Assets_TTM,
    Return_On_Equity_TTM,
    Revenue_TTM,
    Gross_Profit_TTM,
    Diluted_EPS_TTM,
    Quarterly_Earnings_Growth_YOY,
    Quarterly_Revenue_Growth_YOY,
    Analyst_Target_Price,
    Trailing_PE,
    Forward_PE,
    Price_To_Sales_Ratio_TTM,
    Price_To_Book_Ratio,
    EV_To_Revenue,
    EV_To_EBITDA,
    Beta,
    High_52_Week,
    Low_52_Week,
    Moving_Average_50_Day,
    Moving_Average_200_Day,
    Shares_Outstanding,
    Dividend_Date,
    Ex_Dividend_Date
);