create table if not exists price_data (
    tick,
    timestamp,
    open,
    high,
    low,
    close,
    adjusted_close,
    volume,
    dividend_amount,
    primary key (tick, timestamp),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);

create table if not exists earnings_data (
    tick,
    timestamp,--fiscal_Date_Ending,
    reported_Date,
    reported_EPS,
    estimated_EPS,
    surprise,
    surprise_Percentage,
    primary key (tick, timestamp),--fiscal_Date_Ending),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);

create table if not exists cashflow_data (
    tick,
    timestamp,--fiscal_Date_Ending,
    reported_Currency,
    operating_Cashflow,
    payments_For_Operating_Activities,
    proceeds_From_Operating_Activities,
    change_In_Operating_Liabilities,
    change_In_Operating_Assets,
    depreciation_Depletion_And_Amortization,
    capital_Expenditures,
    change_In_Receivables,
    change_In_Inventory,
    profit_Loss,
    cashflow_From_Investment,
    cashflow_From_Financing,
    proceeds_From_Repayments_Of_Short_Term_Debt,
    payments_For_Repurchase_Of_Common_Stock,
    payments_For_Repurchase_Of_Equity,
    payments_For_Repurchase_Of_Preferred_Stock,
    dividend_Payout,
    dividend_Payout_Common_Stock,
    dividend_Payout_Preferred_Stock,
    proceeds_From_Issuance_Of_Common_Stock,
    proceeds_From_Issuance_Of_Long_Term_Debt_And_Capital_Securities_Net,
    proceeds_From_Issuance_Of_Preferred_Stock,
    proceeds_From_Repurchase_Of_Equity,
    proceeds_From_Sale_Of_Treasury_Stock,
    change_In_Cash_And_Cash_Equivalents,
    change_In_Exchange_Rate,
    net_Income,
    primary key (tick, timestamp),--fiscal_Date_Ending),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);

create table if not exists income_statement (
    tick,
    timestamp,--fiscal_Date_Ending,
    reported_Currency,
    gross_Profit,
    total_Revenue,
    cost_Of_Revenue,
    costof_Goods_And_Services_Sold,
    operating_Income,
    selling_General_And_Administrative,
    research_And_Development,
    operating_Expenses,
    investment_Income_Net,
    net_Interest_Income,
    interest_Income,
    interest_Expense,
    non_Interest_Income,
    other_Non_Operating_Income,
    depreciation,
    depreciation_And_Amortization,
    income_Before_Tax,
    income_Tax_Expense,
    interest_And_Debt_Expense,
    net_Income_From_Continuing_Operations,
    comprehensive_Income_Net_Of_Tax,
    ebit,
    ebitda,
    net_Income,
    primary key (tick, timestamp),--fiscal_Date_Ending),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);

create table if not exists balance_sheet(
    tick,
    timestamp,--fiscal_Date_Ending,
    reported_Currency,
    total_Assets,
    total_Current_Assets,
    cash_And_Cash_Equivalents_At_Carrying_Value,
    cash_And_Short_Term_Investments,
    inventory,
    current_Net_Receivables,
    total_Non_Current_Assets,
    property_Plant_Equipment,
    accumulated_Depreciation_Amortization_PPE,
    intangible_Assets,
    intangible_Assets_Excluding_Goodwill,
    goodwill,
    investments,
    long_Term_Investments,
    short_Term_Investments,
    other_Current_Assets,
    other_Non_Current_Assets,
    total_Liabilities,
    total_Current_Liabilities,
    current_Accounts_Payable,
    deferred_Revenue,
    current_Debt,
    short_Term_Debt,
    total_Non_Current_Liabilities,
    capital_Lease_Obligations,
    long_Term_Debt,
    current_Long_Term_Debt,
    long_Term_Debt_Noncurrent,
    short_Long_Term_Debt_Total,
    other_Current_Liabilities,
    other_Non_Current_Liabilities,
    total_Shareholder_Equity,
    treasury_Stock,
    retained_Earnings,
    common_Stock,
    common_Stock_Shares_Outstanding,
    primary key (tick, timestamp),--fiscal_Date_Ending),
    foreign key (tick) references company_data (tick)
        on delete cascade 
        on update no action
);

create table if not exists company_data (
    tick primary key,
    Asset_Type,
    Name,
    Description,
    CIK,
    Exchange,
    Currency,
    Country,
    Sector,
    Industry,
    Address,
    Fiscal_Year_End,
    Latest_Quarter,
    Market_Capitalization,
    EBITDA,
    PE_Ratio,
    PEG_Ratio,
    Book_Value,
    Dividend_Per_Share,
    Dividend_Yield,
    EPS,
    Revenue_Per_Share_TTM,
    Profit_Margin,
    Operating_Margin_TTM,
    Return_On_Assets_TTM,
    Return_On_Equity_TTM,
    Revenue_TTM,
    Gross_Profit_TTM,
    Diluted_EPS_TTM,
    Quarterly_Earnings_Growth_YOY,
    Quarterly_Revenue_Growth_YOY,
    Analyst_Target_Price,
    Trailing_PE,
    Forward_PE,
    Price_To_Sales_Ratio_TTM,
    Price_To_Book_Ratio,
    EV_To_Revenue,
    EV_To_EBITDA,
    Beta,
    High_52_Week,
    Low_52_Week,
    Moving_Average_50_Day,
    Moving_Average_200_Day,
    Shares_Outstanding,
    Dividend_Date,
    Ex_Dividend_Date
);